---

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release
      - apt-transport-https

- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} jammy stable"
    state: present
    update_cache: yes

- name: Install Docker CLI
  apt:
    name:
      - docker-ce-cli
    update_cache: true

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/docker
    - ~{{ ansible_username }}/.docker
    - ~root/.docker

- name: Add local user to docker group
  user:
    name: "{{ ansible_username }}"
    groups: docker
    append: true

- name: Switch to the legacy variant of iptables
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install docker-compose
  pip:
    name:
      - setuptools==58.0.3
      - wheel==0.37.0
      - docker-compose==1.29.2

- name: Set docker aliases
  lineinfile:
    path: "~{{ ansible_username }}/.profile"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: |
        alias d='docker '
      line: |
        alias d='docker '
    - regexp: |
        alias dc='docker-compose '
      line: |
        alias dc='docker-compose '
