---

trigger:
  branches:
    include:
      - "*"

variables:
  - name: imageTag
    value: $(Build.SourceVersion)
      

jobs:
  - job: macBuild
    displayName: Install on MacOS
    dependsOn: linuxBuild
    pool:
      vmImage: macOS-latest
    steps:
      - script: make install
        displayName: Install
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)

  - job: linuxBuild
    displayName: Build devcontainer image
    # dependsOn: macBuild
    # condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Login to DockerHub
        inputs:
          command: login
          containerRegistry: dockerhub

      - script: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
          docker buildx inspect --bootstrap
        displayName: 'Set up Docker Buildx'

      - script: make image/build
        displayName: Build image
        env:
          IMAGE_TAG: $(imageTag)
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          DOCKER_CLI_EXPERIMENTAL: enabled

      - ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/main' ) }}:
          - script: make image/push
            displayName: Push image
            env:
              IMAGE_TAG: $(imageTag)

          - script: make image/tag
            displayName: Retag image to latest
            env:
              OLD_TAG: $(imageTag)
              NEW_TAG: latest

          - script: make image/push
            displayName: Push image with latest tag
            env:
              IMAGE_TAG: latest
