---

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

  - task: Docker@2
    displayName: Login to DockerHub
    inputs:
      command: login
      containerRegistry: dockerhub

  - script: make image/build
    displayName: Build image
    env:
      IMAGE_TAG: $(Build.SourceVersion)

  - script: make image/push
    displayName: Push image with latest tag
    env:
      IMAGE_TAG: latest
