---

trigger:
  branches:
    include:
      - "*"

variables:
  - name: imageTag
    value: $(Build.SourceVersion)
  - name: imageTagMinimal
    value: $(Build.SourceVersion)-minimal

jobs:
  - job: macBuild
    displayName: Install on MacOS
    pool:
      vmImage: macOS-latest
    steps:
      - script: make install
        displayName: Install
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)

  - job: linuxBuild
    displayName: Build devcontainer image
    dependsOn: macBuild
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Login to DockerHub
        inputs:
          command: login
          containerRegistry: dockerhub

      - script: make image/build
        displayName: Build image
        env:
          IMAGE_TAG: $(imageTag)
          GITHUB_TOKEN: $(GITHUB_TOKEN)

      - ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/main' ) }}:
          - script: make image/push
            displayName: Push image
            env:
              IMAGE_TAG: $(imageTag)

          - script: make image/tag
            displayName: Retag image to latest
            env:
              OLD_TAG: $(imageTag)
              NEW_TAG: latest

          - script: make image/push
            displayName: Push image with latest tag
            env:
              IMAGE_TAG: latest

  - job: linuxBuildMinimal
    displayName: Build devcontainer minimal image
    dependsOn: linuxBuild
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Login to DockerHub
        inputs:
          command: login
          containerRegistry: dockerhub

      - script: make image/build
        displayName: Build image
        env:
          IMAGE_TAG: $(imageTagMinimal)
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          PLAYBOOK: minimal.yaml

      - ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/main' ) }}:
        - script: make image/push
          displayName: Push image
          env:
            IMAGE_TAG: $(imageTagMinimal)

        - script: make image/tag
          displayName: Retag image to latest
          env:
            OLD_TAG: $(imageTagMinimal)
            NEW_TAG: latest-minimal

        - script: make image/push
          displayName: Push image with latest tag
          env:
            IMAGE_TAG: latest-minimal