---
- name: Determine whether OpenShift CLI is already installed with the desired version
  shell: "set -o pipefail && (oc version || true) | (grep {{ openshift_cli_version }} || true) | wc -l"
  args:
    executable: /bin/bash
  register: oc_installed
  changed_when: oc_installed.rc != 0

- name: Install OpenShift CLI binary
  when: oc_installed.stdout != '1'
  block:
    - name: Create temporary directory for OpenShift CLI binary
      delegate_to: localhost
      become: false
      tempfile:
        state: directory
        suffix: ocbin
      register: tmpdir_ocbin

    - name: Download OpenShift CLI binary to controller
      become: false
      delegate_to: localhost
      unarchive:
        src: "https://github.com/openshift/origin/releases/download/{{ openshift_cli_version }}/openshift-origin-client-tools-{{ openshift_cli_version }}-0cbc58b-linux-64bit.tar.gz"
        dest: '{{ tmpdir_ocbin.path }}'
        remote_src: true
        list_files: yes
      register: archive_contents

    - name: Copy oc binary to remote
      copy:
        src: "{{ tmpdir_ocbin.path }}/{{ archive_contents.files[0].split('/')[0] }}/oc"
        dest: /usr/local/bin/oc
        mode: '0751'

  always:
    - name: Recursively remove temporary OpenShift CLI binary directory
      become: false
      delegate_to: localhost
      file:
        path: "{{ tmpdir_ocbin.path }}"
        state: absent
