---
- name: Determine whether k9s is already installed with the desired version
  shell: "set -o pipefail && (k9s version || true) | (grep {{ k9s_version }} || true) | wc -l"
  args:
    executable: "{{ ansible_user_shell }}"
  register: k9s_installed
  changed_when: k9s_installed.rc != 0

- name: Install k9s
  when: k9s_installed.stdout != '1'
  shell: |
    mise use -g k9s@{{ k9s_version }}
  args:
    executable: "{{ ansible_user_shell }}"
