---
- name: Determine whether kind is already installed with the desired version
  shell: "set -o pipefail && (kind version || true) | (grep {{ kind_version }} || true) | wc -l"
  args:
    executable: "{{ ansible_user_shell }}"
  register: kind_installed
  changed_when: kind_installed.rc != 0

- name: Install kind
  when: kind_installed.stdout != '1'
  shell: |
    mise use -g kind@{{ kind_version }}
  args:
    executable: "{{ ansible_user_shell }}"