---
- name: Install Git
  block:
    - name: Install Git package
      become: "{{ should_be_root }}"
      package:
        name: git
        state: latest

- name: Set alias g for Git
  lineinfile:
    path: "~{{ ansible_username }}/.{{ shell_name }}rc"
    regexp: |
      alias g='git '
    line: |
      alias g='git '

- name: Install Git Credential Manager
  when: install_gcm
  include_tasks: install_gcm.yaml
