---
- name: Install Git
  block:
    - name: Install Git package
      become: "{{ should_be_root }}"
      package:
        name: git
        state: latest

- name: Ensure ~/.profile file exists
  file:
    path: "~{{ ansible_username }}/.profile"
    state: touch

- name: Set alias g for Git in ~/.profile
  lineinfile:
    path: "~{{ ansible_username }}/.profile"
    regexp: |
      alias g='git '
    line: |
      alias g='git '

- name: Install Git Credential Manager
  when: install_gcm
  include_tasks: install_gcm.yaml
