---
- name: Install Git
  block:
    - name: Install Git apt package
      become: true
      apt:
        name: git

- name: Set alias g for Git
  lineinfile:
    path: "~{{ ansible_username }}/.profile"
    regexp: |
      alias g='git '
    line: |
      alias g='git '

- name: Determine whether Git Credential Manager is already installed with the desired version
  shell: "set -o pipefail && (git-credential-manager --version || true) | (grep {{ gcm_version }} || true) | wc -l"
  args:
    executable: /bin/bash
  register: gcm_installed
  changed_when: gcm_installed.rc != 0

- name: Install Git Credential Manager
  when: gcm_installed.stdout != '1'
  unarchive:
    src: https://github.com/git-ecosystem/git-credential-manager/releases/download/v{{ gcm_version }}/gcm-linux_amd64.{{ gcm_version }}.tar.gz
    dest: /usr/local/bin/
    remote_src: true

- name: Init Git Credential Manager
  shell: "git-credential-manager configure"
  become: false
  args:
    executable: /bin/bash

- name: Configure Git Credential Manager
  lineinfile:
    path: "~{{ ansible_username }}/.profile"
    regexp: |
      export GCM_CREDENTIAL_STORE=plaintext
    line: |
      export GCM_CREDENTIAL_STORE=plaintext

- name: Create home Git directory if it does not exist
  file:
    path: "~{{ ansible_username }}/git"
    state: directory
    mode: '0755'
