---

- name: Esnure ~{{ ansible_username }}/.{{ shell_name }}rc exists
  stat:
    path: ~{{ ansible_username }}/.{{ shell_name }}rc
  register: stat_result

- name: Ensure direnv is set in ~{{ ansible_username }}/.{{ shell_name }}rc
  when: stat_result.stat.exists
  lineinfile:
    path: "~{{ ansible_username }}/.{{ shell_name }}rc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: |
        eval "\$\(direnv hook {{ shell_name }}\)"
      line: |
        eval "$(direnv hook {{ shell_name }})"
