---

- name: Esnure ~{{ ansible_username }}/.profile exists
  stat:
    path: ~{{ ansible_username }}/.profile
  register: stat_result

- name: Ensure direnv is set in ~{{ ansible_username }}/.profile
  when: stat_result.stat.exists
  lineinfile:
    path: "~{{ ansible_username }}/.profile"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: |
        eval "\$\(direnv hook {{ shell_name }}\)"
      line: |
        eval "$(direnv hook {{ shell_name }})"
