---

- name: Install NodeJS versions
  shell: |
    eval "$(~/.local/bin/mise activate {{ shell_name }})" && \
    mise install node@{{ item }}
  become: false
  args:
    executable: "{{ ansible_user_shell }}"
  loop: "{{ nodejs_versions }}"

- name: Npm install
  shell: |
    eval "$(~/.local/bin/mise activate {{ shell_name }})" && \
    npm install {{ item }}
  become: false
  args:
    executable: "{{ ansible_user_shell }}"
  loop: "{{ nodejs_packages }}"
