---

- name: Go install tools
  shell: |
    eval "$(~/.local/bin/mise activate {{ shell_name }})" && \
    go install {{ item }}
  become: false
  args:
    executable: "{{ ansible_user_shell }}"
  loop: "{{ go_install }}"
