---
- name: Install pre-req packages
  become: '{{ should_be_root }}'
  package:
    name: curl

- name: Determine whether mise is already installed
  shell: "set -o pipefail && (mise version || true) | wc -l"
  args:
    executable: "{{ ansible_user_shell }}"
  register: mise_installed
  changed_when: mise_installed.rc != 0

- name: Install Mise
  when: mise_installed.stdout != '1'
  block:
    - name: Install mise
      become: true
      shell: |
        curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
      args:
        executable: "{{ ansible_user_shell }}"

    - name: Ensure ~/.{{ shell_name}}rc file exists
      file:
        path: "~{{ ansible_username }}/.{{ shell_name }}rc"
        state: touch

    - name: Ensure mise is set in ~/.{{ shell_name }}rc
      lineinfile:
        path: "~{{ ansible_username }}/.bashrc"
        regexp: local\/bin\/mise activate 
        line: |
          eval "$(mise activate bash)"

- name: Mise use {{ item }}
  shell: |
    mise use {{ item }}
  args:
    executable: "{{ ansible_user_shell }}"
  loop: "{{ mise_use }}"