- name: Install autojump
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Install apt package
      become: true
      apt:
        name: python-is-python3

    - name: Create a directory if it does not exist
      file:
        path: ~{{ ansible_username }}/.zsh
        state: directory
        mode: '0755'

    - name: Clone autojump repo
      git:
        repo: https://github.com/wting/autojump.git
        dest: ~{{ ansible_username }}/.zsh/autojump

    - name: Execute install script autojump
      become: false
      shell: "SHELL=/bin/zsh python3 ./install.py"
      args:
        chdir: ~{{ ansible_username }}/.zsh/autojump
        executable: /bin/zsh

    - name: Ensure ~/.zshrc file exists
      file:
        path: "~{{ ansible_username }}/.zshrc"
        state: touch

    - name: Ensure autojump is set in ~/.zshrc
      lineinfile:
        path: "~{{ ansible_username }}/.zshrc"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: |
            autojump.sh \]\] && source
          line: |
            [[ -s ~{{ ansible_username }}/.autojump/etc/profile.d/autojump.sh ]] && source ~{{ ansible_username }}/.autojump/etc/profile.d/autojump.sh
        - regexp: |
            autoload -U compinit && compinit -u
          line: |
            autoload -U compinit && compinit -u

- name: Install autojump
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Install homebrew package
      homebrew:
        name: autojump

    - name: Ensure autojump is set in ~/.zshrc
      lineinfile:
        path: "~{{ ansible_username }}/.zshrc"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: |
            profile\.d\/autojump\.sh
          line: |
            [ -f $(brew --prefix)/etc/profile.d/autojump.sh ] && . $(brew --prefix)/etc/profile.d/autojump.sh