---

- name: Apply tags to tasks within included file
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ ansible_username }}"
        oh_my_zsh:
          theme: agnoster
          plugins:
            - git
            - docker
            - autojump
            - zsh-syntax-highlighting
            - zsh-autosuggestions
          update_mode: reminder
          update_frequency: 3
          write_zshrc: true

- name: Install autojump
  when: install_autojump
  include_tasks: install_autojump.yaml

- name: Install pure theme
  when: install_pure_theme
  include_tasks: install_pure_theme.yaml

- name: Install zsh-autosuggestions
  when: install_zsh_autosuggestions
  include_tasks: install_zsh_autosuggestions.yaml

- name: Install ZSH Syntax Highlighting
  when: install_zsh_syntax_highlighting
  include_tasks: install_zsh_syntax_highlighting.yaml

- name: Source ~/.profile
  when: ansible_distribution == 'MacOSX'
  lineinfile:
    path: "~{{ ansible_username }}/.zshrc"
    regexp: |
      && emulate sh -c 'source ~/.profile
    line: |
      [[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'
