---

- name: Install oh my zsh
  when: ansible_distribution == 'Ubuntu'
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ ansible_username }}"
        oh_my_zsh:
          theme: agnoster
          update_mode: reminder
          update_frequency: 3
          write_zshrc: false

- name: Install oh my zsh
  when: ansible_distribution == 'MacOSX'
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ ansible_username }}"
        oh_my_zsh:
          theme: agnoster
          update_mode: reminder
          update_frequency: 3
          write_zshrc: false

- name: Ensure ~/.zshrc file exists
  file:
    path: "~{{ ansible_username }}/.zshrc"
    state: touch

- name: Init ~/.zshrc
  lineinfile:
    path: "~{{ ansible_username }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: |
        export ZSH\=\"\$HOME\/\.oh\-my\-zsh\"
      line: |
        export ZSH="$HOME/.oh-my-zsh"
    - regexp: |
        plugins\=\(git docker\)
      line: |
        plugins=(git docker)

- name: Install autojump
  when: install_autojump
  include_tasks: install_autojump.yaml

- name: Install pure theme
  when: install_pure_theme
  include_tasks: install_pure_theme.yaml

- name: Install zsh-autosuggestions
  when: install_zsh_autosuggestions
  include_tasks: install_zsh_autosuggestions.yaml

- name: Install ZSH Syntax Highlighting
  when: install_zsh_syntax_highlighting
  include_tasks: install_zsh_syntax_highlighting.yaml

- name: Source ~/.profile
  when: ansible_distribution == 'Ubuntu'
  lineinfile:
    path: "~{{ ansible_username }}/.zshrc"
    regexp: |
      && emulate sh -c 'source ~/.profile
    line: |
      [[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

- name: Source oh-my-zsh
  lineinfile:
    path: "~{{ ansible_username }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: |
        source \$ZSH\/oh\-my\-zsh\.sh
      line: |
        source $ZSH/oh-my-zsh.sh