---

- name: Apply tags to tasks within included file
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ ansible_username }}"
        oh_my_zsh:
          theme: agnoster
          plugins:
            - git
            - docker
            - autojump
            - zsh-syntax-highlighting
            - zsh-autosuggestions
          update_mode: reminder
          update_frequency: 3
          write_zshrc: true

- name: Install autojump
  include_tasks: install_autojump.yaml

- name: Install pure theme
  include_tasks: install_pure_theme.yaml

- name: Install zsh-auto-suggestions
  include_task: install_zsh_auto_suggestions.yaml

- name: Install ZSH Syntax Highlighting
  include_task: install_zsh_syntax_highlighting.yaml

- name: Source .bashrc
  lineinfile:
    path: "~{{ ansible_username }}/.zshrc"
    regexp: |
      && emulate sh -c 'source ~/.bashrc
    line: |
      [[ -e ~/.bashrc ]] && emulate sh -c 'source ~/.bashrc'
