---

- name: Print facts
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print all available facts
      debug:
        var: ansible_facts

- name: Setup work environment
  hosts: localhost
  vars:
    should_be_root:  "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  become: false
  gather_facts: true
  pre_tasks:
    - name: Set ansible_username
      set_fact:
        ansible_username: "{{ lookup('env', 'USER') | default(ansible_user_id, true) }}"
    - name: Set the shell name
      set_fact:
        shell_name: "{{ ansible_user_shell | regex_replace('^.*/', '') }}"
    - name: Set architecture fact based on ansible_architecture
      set_fact:
        architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  roles:

    - role: packages
      packages:
        apt:
          - tar
          - curl
          - findutils
          - unzip
          - coreutils
          - dnsutils
          - net-tools
          - rsync
          - wget
          - vim
          - upx
        homebrew:
          - gnu-tar
          - curl
          - findutils
          - unzip 
          - coreutils
          # - dnsutils # Not available in Brew
          # - net-tools # Only available via Brew for Linux distros
          - rsync
          - wget
          # - vim   # Already pre-installed
          - upx

    - role: zsh
      install_autojump: true
      install_pure_theme: true
      install_zsh_autosuggestions: true
      install_zsh_syntax_highlighting: true

    - role: mise
      mise_use:
        - kind@0.25.0
        - kubectl@1.29.11
        - yq@4.44.5
        - helm@3.16.3
        - jq@1.7.1
        - k9s@0.32.7
        - gomigrate@4.18.1
        - sops@3.9.2
        - terraform@1.10.1
        - argocd@2.13.1
        - kubeconform@0.7.0
        - shellcheck@0.10.0
        - kustomize@5.5.0
        - kubectx@0.9.5
        - kubens@0.9.5
        - ruff@0.9.9
        - k6@1.0.0
        - vault@1.19.5
        - mc@2025-05-21T01-59-54Z
        - podman@5.5.0
        - ollama@0.9.0
        - glab@1.59.2

    - role: go
      go_global: "1.23.3"
      go_install:
        - github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.2

    - role: python
      python_global: "3.13.0"
      python_versions:
        - "3.12.0"
        - "3.11.0"
        - "3.10.0"
      python_packages:
        - setuptools==58.0.3
        - wheel==0.37.0
        - requests
      python_cli_tools: []

    - role: mise
      mise_use:
        - uv
        - poetry@2.1.3      
        - pipx:codespell@2.4.1
        - pipx:commitizen@4.4.1
        - pipx:pre-commit@4.1.0
        - pipx:yamllint@1.37.0
        - pipx:black@25.1.0
        - pipx:ipython@9.3.0


    - role: nodejs
      nodejs_global: "20.12.1"
      nodejs_versions: []
      nodejs_packages: []

    - role: mise
      mise_use:
        - npm:markdownlint-cli@0.44.0

    - role: direnv
      direnv_version: "2.35.0"

    - role: openshift
      openshift_version: 4.15.0-0.okd-2024-03-10-010116

    # - role: azure-cli
    #   install_az_cli_devops_extension: true

    - role: docker
      install_docker_compose: true
