---

- name: Print facts
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print all available facts
      debug:
        var: ansible_facts

- name: Setup work environment
  hosts: localhost
  vars:
    should_be_root:  "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  # become: "{{ should_be_root }}"
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set ansible_username
      set_fact:
        ansible_username: "{{ lookup('env', 'USER') | default(ansible_user_id, true) }}"
        # ansible_os_family: Debian
        # os_family: Debian
    - name: Set the shell name
      set_fact:
        shell_name: "{{ lookup('env', 'SHELL') | regex_replace('^.*/', '') }}"

    - name: Set architecture fact based on ansible_architecture
      set_fact:
        architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  roles:
    - role: mise
      install: 
        - kind@0.25.0 --global
        - kubectl@1.29.11 --global
        - yq@4.44.5 --global
        - helm@3.16.3 --global
        - direnv@2.35.0 --global
        - python@3.13.0 --global
        - go@1.23.3 --global
        - node@20.12.1 --global
        - jq@1.7.1 --global


    # - role: mise
    #   install: pipx@latest --global --force
    # - role: pipx
    #   install: ansible@4.6.0

    # Works on MacOS
    # - packages
    # - tar
    # - nodejs
    # - go
    # - openshift
    # - kind
    # - kubectl
    # - k9s
    # - helm
    # - direnv

    # Works on Ubuntu
    # - packages
    # - tar
    # - nodejs
    # - go
    # - openshift
    # - kind
    # - kubectl
    # - k9s
    # - helm
    # - direnv
    # - python
    # - az
    # - zsh


    
    ####T TODO
    # - certs
    # - ssh
    # - az
    # - zsh
    # - python
    # - docker-cli
    # - docker