---

packages:

  apt:
    - tar
    - curl
    - findutils
    - unzip
    - coreutils
    - dnsutils
    - jq
    - net-tools
    - rsync
    - wget
    - vim

  homebrew:
    - curl
    - findutils
    - unzip 
    - coreutils
    # - dnsutils - not available in brew
    - jq
    - net-tools
    - rsync
    - wget
    - vim